# Generated by Django 6.1 on 2026-08-26 08:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('overall_ready_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tayyorgarlik bali (0-100)')),
                ('streak_count', models.IntegerField(default=0, verbose_name='Ketma-ketlik (streak)')),
                ('delta', models.CharField(default='0', max_length=100, verbose_name="O'zgarish miqdori va sababi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='accounts.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Rivojlanish jurnali',
                'verbose_name_plural': 'Rivojlanish jurnallari',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('grammar', 'Grammar')], max_length=50, verbose_name="Ko'nikma")),
                ('current_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Joriy ball (0-100)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_scores', to='accounts.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "Ko'nikma bali",
                'verbose_name_plural': "Ko'nikma ballari",
                'ordering': ['student', 'skill'],
                'unique_together': {('student', 'skill')},
            },
        ),
    ]
