"""
Models for personalized study plans.
"""
from django.db import models
from django.utils import timezone

class StudyPlan(models.Model):
    """
    Personalized study plan generated by AI based on student diagnostic profile and goals.
    """
    student = models.ForeignKey(
        'accounts.Student',
        on_delete=models.CASCADE,
        related_name='study_plans',
        verbose_name="O'quvchi"
    )
    goal = models.TextField(verbose_name="O'quv maqsadi")
    start_date = models.DateField(default=timezone.localdate, verbose_name="Boshlanish sanasi")
    target_date = models.DateField(verbose_name="Maqsad sanasi")
    generated_by_ai = models.JSONField(default=dict, verbose_name="AI tomonidan tuzilgan reja")
    active = models.BooleanField(default=True, verbose_name="Faol reja")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan vaqt")

    class Meta:
        verbose_name = "O'quv rejasi"
        verbose_name_plural = "O'quv rejalari"
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.student.user.first_name} — Reja ({self.start_date} dan {self.target_date} gacha)"
