# Generated by Django 6.1 on 2026-08-26 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(verbose_name="O'quv maqsadi")),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Boshlanish sanasi')),
                ('target_date', models.DateField(verbose_name='Maqsad sanasi')),
                ('generated_by_ai', models.JSONField(default=dict, verbose_name='AI tomonidan tuzilgan reja')),
                ('active', models.BooleanField(default=True, verbose_name='Faol reja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='accounts.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "O'quv rejasi",
                'verbose_name_plural': "O'quv rejalari",
                'ordering': ['-created_at'],
            },
        ),
    ]
