# Generated by Django 6.1 on 2026-08-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='timeline_months',
            field=models.IntegerField(default=6, verbose_name='Reja davomiyligi (oylar)'),
        ),
    ]
