# Generated by Django 6.1 on 2026-08-27 08:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_student_birth_date_student_birth_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('ielts', 'IELTS Academic (Listening, Reading, Writing)'), ('sat', 'SAT Digital (Reading & Writing, Math)'), ('toefl', 'TOEFL iBT')], default='ielts', max_length=20, verbose_name='Imtihon turi')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('total_duration_seconds', models.IntegerField(default=9000, verbose_name='Rejalashtirilgan jami vaqt (soniya)')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda (In Progress)'), ('completed', 'Tugallangan (Completed)'), ('abandoned', 'Tashlab ketilgan (Abandoned)')], default='in_progress', max_length=20, verbose_name='Holat')),
                ('overall_band_score', models.FloatField(blank=True, null=True, verbose_name='Umumiy ball (Band Score)')),
                ('ai_summary_feedback', models.TextField(blank=True, verbose_name='AI umumiy xulosasi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to='accounts.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Mock Imtihon',
                'verbose_name_plural': 'Mock Imtihonlar',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MockExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('listening', 'Listening (Eshitish)'), ('reading', "Reading (O'qish)"), ('writing', 'Writing (Insho va yozish)'), ('speaking', 'Speaking (Nutq)')], max_length=20, verbose_name="Bo'lim turi")),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ketma-ketlik tartibi')),
                ('time_limit_seconds', models.IntegerField(default=3600, verbose_name='Vaqt chegarasi (soniya)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name="Bo'lim savollari va matnlari (JSON)")),
                ('student_response', models.JSONField(blank=True, default=dict, verbose_name="O'quvchi javoblari (JSON/Text)")),
                ('section_score', models.FloatField(blank=True, null=True, verbose_name="Bo'lim bali (Band 0.0 - 9.0)")),
                ('ai_feedback', models.TextField(blank=True, verbose_name='AI tahlili va xatolar izohi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallangan'), ('skipped', "O'tkazib yuborilgan")], default='pending', max_length=20, verbose_name="Bo'lim holati")),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mock_exams.mockexam', verbose_name='Mock Imtihon')),
            ],
            options={
                'verbose_name': "Mock Imtihon Bo'limi",
                'verbose_name_plural': "Mock Imtihon Bo'limlari",
                'ordering': ['order'],
            },
        ),
    ]
