# Generated by Django 6.1 on 2026-08-26 08:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('study_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Vazifa sanasi')),
                ('task_type', models.CharField(choices=[('grammar_drill', 'Grammar Drill'), ('reading_comprehension', 'Reading Comprehension')], max_length=50, verbose_name='Vazifa turi')),
                ('content', models.JSONField(default=dict, verbose_name='Vazifa mazmuni')),
                ('completed', models.BooleanField(default=False, verbose_name='Bajarildi')),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Natija bali (0-100)')),
                ('student_answer', models.TextField(blank=True, default='', verbose_name="O'quvchi javobi")),
                ('ai_feedback', models.TextField(blank=True, default='', verbose_name='AI tahlili va tushuntirishi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='accounts.student', verbose_name="O'quvchi")),
                ('study_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks', to='study_plans.studyplan', verbose_name="O'quv rejasi")),
            ],
            options={
                'verbose_name': 'Kunlik vazifa',
                'verbose_name_plural': 'Kunlik vazifalar',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
