# Generated by Django 6.1 on 2026-08-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='track',
            field=models.CharField(choices=[('track_a', 'Track A: Imtihon tayyorgarligi (Test Prep)'), ('track_b', 'Track B: Universitet arizasi va Hujjatlar (Application Prep)'), ('general', 'Umumiy vazifa (General)')], default='track_a', max_length=20, verbose_name="Yo'nalish (Track)"),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='task_type',
            field=models.CharField(choices=[('grammar_drill', 'Grammar Drill'), ('reading_comprehension', 'Reading Comprehension'), ('vocabulary_drill', "Lug'at boyligi (Vocabulary Drill)"), ('listening_drill', "Eshitish ko'nikmasi (Listening Drill)"), ('speaking_drill', 'Nutq va talaffuz (Speaking Drill)'), ('writing_drill', 'Yozish mashqi (Writing Drill)'), ('mock_test', 'Sinov testi (Mock Exam)'), ('essay_milestone', 'Insho yozish (SOP / Motivation Letter)'), ('extracurricular', 'Darsdan tashqari faoliyat loyihasi'), ('lor_request', 'Tavsiyanoma tayyorlash (LOR)'), ('document_prep', "Hujjatlar to'plash va tarjima"), ('university_research', 'Universitet va grant tahlili'), ('application_submit', 'Arizani topshirish (Application Submission)')], max_length=50, verbose_name='Vazifa turi'),
        ),
    ]
