# Generated by Django 6.1 on 2026-08-28 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_birth_date_student_birth_year_and_more'),
        ('tasks', '0002_dailytask_track_alter_dailytask_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('part1_intro', 'Part 1 (Introduction and Interview)'), ('part2_cue_card', 'Part 2 (Cue Card Monologue)'), ('part3_discussion', 'Part 3 (Two-way Discussion)')], default='part2_cue_card', max_length=20, verbose_name='Qism')),
                ('prompt_text', models.TextField(verbose_name='Savol/Cue Card')),
                ('prep_time_seconds', models.IntegerField(default=60, verbose_name='Tayyorgarlik vaqti (soniya)')),
                ('speak_time_seconds', models.IntegerField(default=120, verbose_name='Gapirish vaqti (soniya)')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='speaking_audio/%Y/%m/', verbose_name='Audio yozuv')),
                ('transcript', models.TextField(blank=True, default='', verbose_name='Transkript (Matn)')),
                ('ai_feedback', models.TextField(blank=True, default='', verbose_name='AI baholashi')),
                ('band_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Band Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_sessions', to='accounts.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Speaking sessiyasi',
                'verbose_name_plural': 'Speaking sessiyalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
