# Generated by Django 6.1 on 2026-08-26 08:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqami')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Familiya')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email manzili')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Xodim maqomi')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser maqomi')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Ro'yxatdan o'tgan sana")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, choices=[(9, '9-sinf'), (10, '10-sinf'), (11, '11-sinf')], null=True, verbose_name='Sinf')),
                ('target_countries', models.JSONField(blank=True, default=list, verbose_name='Maqsad qilingan davlatlar')),
                ('target_program_type', models.CharField(blank=True, choices=[('grant', "To'liq Grant / Stipendiya"), ('partial_grant', 'Qisman Grant'), ('paid', "To'lovli"), ('exchange', 'Almashinuv dasturi')], default='grant', max_length=100, verbose_name='Maqsad qilingan dastur turi')),
                ('english_level', models.CharField(blank=True, choices=[('beginner', 'Beginner (A1-A2)'), ('intermediate', 'Intermediate (B1-B2)'), ('advanced', 'Advanced (C1-C2)')], default='beginner', max_length=50, verbose_name='Ingliz tili darajasi')),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='Onboarding yakunlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "O'quvchi profili",
                'verbose_name_plural': "O'quvchilar profillari",
                'ordering': ['-created_at'],
            },
        ),
    ]
