# Generated by Django 6.1 on 2026-08-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notification_daily_reminders',
            field=models.BooleanField(default=True, verbose_name='Kunlik vazifa eslatmalari'),
        ),
        migrations.AddField(
            model_name='student',
            name='notification_email_enabled',
            field=models.BooleanField(default=True, verbose_name='Email eslatmalari'),
        ),
        migrations.AddField(
            model_name='student',
            name='notification_reminder_time',
            field=models.CharField(blank=True, default='20:00', max_length=10, verbose_name='Eslatma vaqti'),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_language',
            field=models.CharField(default='uz', max_length=10, verbose_name="Afzal ko'rilgan til"),
        ),
    ]
