# Generated by Django 6.1 on 2026-08-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_notification_daily_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name="Tug'ilgan yili"),
        ),
        migrations.AddField(
            model_name='student',
            name='budget_preference',
            field=models.CharField(blank=True, choices=[('toliq_grant', "To'liq Grant (Full Scholarship)"), ('qisman_grant', 'Qisman Grant (Partial Tuition / Discount)'), ('ozi_moliyalashtirish', "O'zi moliyalashtirish (Self-funded)")], default='toliq_grant', max_length=50, verbose_name='Byudjet imkoniyati / Afzallik'),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Shahar / Tuman'),
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.JSONField(blank=True, default=list, verbose_name='Qiziqishlar va xobbilar'),
        ),
        migrations.AddField(
            model_name='student',
            name='plan_timeline_months',
            field=models.IntegerField(default=6, verbose_name='Reja davomiyligi (oylar)'),
        ),
        migrations.AddField(
            model_name='student',
            name='planned_test_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rejalashtirilgan imtihon sanasi'),
        ),
        migrations.AddField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, choices=[('toshkent_sh', 'Toshkent shahri'), ('toshkent_vil', 'Toshkent viloyati'), ('samarqand', 'Samarqand'), ('buxoro', 'Buxoro'), ('fargona', "Farg'ona"), ('andijon', 'Andijon'), ('namangan', 'Namangan'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('xorazm', 'Xorazm'), ('navoiy', 'Navoiy'), ('jizzax', 'Jizzax'), ('sirdaryo', 'Sirdaryo'), ('qoraqalpogiston', "Qoraqalpog'iston")], default='', max_length=50, verbose_name='Viloyat / Hudud'),
        ),
        migrations.AddField(
            model_name='student',
            name='target_career',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Kelajak kasbi / Maqsad'),
        ),
        migrations.AddField(
            model_name='student',
            name='target_field_of_study',
            field=models.CharField(blank=True, choices=[('cs_it', 'Dasturlash va IT'), ('ai_ds', "Sun'iy intellekt va Data Science"), ('medicine', 'Tibbiyot va Salomatlik'), ('business_finance', 'Biznes va Moliya'), ('engineering', 'Muhandislik va Biotexnologiya'), ('international_law', 'Xalqaro munosabatlar va Huquq'), ('natural_sciences', 'Aniq va tabiiy fanlar'), ('humanities_arts', "Gumanitar fanlar va San'at"), ('education', "Pedagogika va Ta'lim")], default='', max_length=100, verbose_name="Kelajak o'qish yo'nalishi"),
        ),
    ]
