# Generated by Django 6.1 on 2026-08-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0002_studentprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Qo'llanma sarlavhasi")),
                ('category', models.CharField(choices=[('essay_writing', 'Insho va SOP yozish'), ('interview_prep', 'Intervyuga tayyorgarlik'), ('visa_process', 'Viza va elchixona jarayoni'), ('general_tips', 'Foydali maslahatlar va strategiyalar')], default='general_tips', max_length=50, verbose_name='Kategoriya')),
                ('summary', models.CharField(blank=True, max_length=400, verbose_name='Qisqacha mazmun')),
                ('content', models.TextField(verbose_name="To'liq matn / Qo'llanma")),
                ('author_name', models.CharField(default='Kelajak Ekspertlar Guruhi', max_length=100, verbose_name='Muallif / Ekspert')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('related_programs', models.ManyToManyField(blank=True, related_name='resources', to='programs.program', verbose_name='Tegishli grant dasturlari')),
            ],
            options={
                'verbose_name': "Resurs / Qo'llanma",
                'verbose_name_plural': 'Resurslar kutubxonasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
