# Generated by Django 6.1 on 2026-08-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('essay_writing', 'Insho va SOP yozish'), ('interview_prep', 'Intervyuga tayyorgarlik'), ('visa_process', 'Viza va elchixona jarayoni'), ('general_tips', 'Foydali maslahatlar va strategiyalar'), ('ielts_reading', 'IELTS: Reading strategiyalari'), ('ielts_writing', 'IELTS: Writing (Task 1 & 2)'), ('ielts_listening', "IELTS: Listening ko'nikmalari"), ('ielts_speaking', 'IELTS: Speaking (Part 1-3)'), ('grammar_vocab', "Grammatika va lug'at boyligi")], default='general_tips', max_length=50, verbose_name='Kategoriya'),
        ),
    ]
