# Generated by Django 6.1 on 2026-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='related_resources',
            field=models.ManyToManyField(blank=True, to='resources.resource', verbose_name="Tegishli resurslar (o'qish ketma-ketligi)"),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('essay_writing', 'Insho va SOP yozish'), ('interview_prep', 'Intervyuga tayyorgarlik'), ('visa_process', 'Viza va elchixona jarayoni'), ('general_tips', 'Foydali maslahatlar va strategiyalar'), ('ielts_reading', 'IELTS: Reading strategiyalari'), ('ielts_writing', 'IELTS: Writing (Task 1 & 2)'), ('ielts_listening', "IELTS: Listening ko'nikmalari"), ('ielts_speaking', 'IELTS: Speaking (Part 1-3)'), ('grammar_vocab', "Grammatika va lug'at boyligi"), ('dtm_prep', "DTM tayyorgarligi va yo'nalish tanlash"), ('top_university_strategy', 'TOP universitetlarga tayyorlash strategiyasi'), ('portfolio_prep', 'Portfolio tayyorlash (Art/Design)'), ('europe_admissions', 'Yevropa universitetlari (DAAD, Campus France, va boshqalar)'), ('east_asia_admissions', 'Osiyo (Koreya, Yaponiya, Xitoy) universitetlari')], default='general_tips', max_length=50, verbose_name='Kategoriya'),
        ),
    ]
