# Generated by Django 6.1 on 2026-09-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_related_resources_alter_resource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='author_name',
            field=models.CharField(default='UniMentor Ekspertlar Guruhi', max_length=100, verbose_name='Muallif / Ekspert'),
        ),
    ]
