# Generated by Django 6.1 on 2026-08-27 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_student_notification_daily_reminders_and_more'),
        ('programs', '0002_studentprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('essay', 'Insho (SOP / Personal Statement)'), ('motivation_letter', 'Motivatsion xat (Motivation Letter)'), ('recommendation', 'Tavsiyanoma (Recommendation Letter)'), ('transcript', 'Baholar tabeli (Academic Transcript)'), ('certificate', 'Sertifikat (IELTS / SAT / Boshqa)'), ('other', 'Boshqa hujjat')], default='essay', max_length=50, verbose_name='Hujjat turi')),
                ('title', models.CharField(max_length=255, verbose_name='Hujjat nomi')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fayl')),
                ('content', models.TextField(blank=True, verbose_name='Hujjat matni (Insho/Xat)')),
                ('version', models.IntegerField(default=1, verbose_name='Versiya')),
                ('ai_feedback', models.TextField(blank=True, verbose_name='AI tahlili va tavsiyalari')),
                ('status', models.CharField(choices=[('draft', 'Qoralama (Draft)'), ('under_review', 'Tekshiruvda (AI Review)'), ('final', 'Tayyor (Final)')], default='draft', max_length=30, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('linked_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_documents', to='programs.program', verbose_name="Bog'langan dastur")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['-updated_at'],
            },
        ),
    ]
