# Generated by Django 6.1 on 2026-08-31 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('essay', 'Insho (SOP / Personal Statement)'), ('motivation_letter', 'Motivatsion xat (Motivation Letter)'), ('recommendation', 'Tavsiyanoma (Recommendation Letter)'), ('transcript', 'Baholar tabeli (Academic Transcript)'), ('certificate', 'Sertifikat (IELTS / SAT / Boshqa)'), ('portfolio', 'Portfolio (Art / Design / Architecture)'), ('other', 'Boshqa hujjat')], default='essay', max_length=50, verbose_name='Hujjat turi'),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Asar/Loyiha nomi')),
                ('file', models.FileField(upload_to='portfolio_items/', verbose_name='Fayl (rasm/video/pdf)')),
                ('medium', models.CharField(blank=True, max_length=100, verbose_name='Muhit/Material (Medium)')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Tugatilgan sana')),
                ('description', models.TextField(blank=True, verbose_name='Loyiha tavsifi')),
                ('ai_feedback', models.TextField(blank=True, verbose_name='AI tahlili va tavsiyalari')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='documents.document', verbose_name='Portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio qismi',
                'verbose_name_plural': 'Portfolio qismlari',
            },
        ),
    ]
