# Generated by Django 6.1 on 2026-08-26 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', "O'quvchi"), ('ai', 'AI Mentor')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Xabar matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_messages', to='accounts.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Mentor xabari',
                'verbose_name_plural': 'Mentor xabarlari',
                'ordering': ['created_at'],
            },
        ),
    ]
