# Generated by Django 6.1 on 2026-08-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Dastur nomi')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('type', models.CharField(choices=[('grant', "To'liq Grant / Stipendiya"), ('partial_grant', 'Qisman Grant'), ('paid', "To'lovli"), ('exchange', 'Almashinuv dasturi')], default='grant', max_length=100, verbose_name='Dastur turi')),
                ('requirements', models.JSONField(blank=True, default=dict, verbose_name='Talablar')),
                ('deadline', models.CharField(blank=True, max_length=100, verbose_name='Topshirish muddati')),
                ('source_url', models.URLField(max_length=500, verbose_name='Rasmiy manba havolasi')),
                ('last_verified_date', models.DateField(verbose_name='Oxirgi tekshirilgan sana')),
                ('verified_by', models.CharField(default='admin', max_length=150, verbose_name='Tekshiruvchi admin')),
            ],
            options={
                'verbose_name': "Ta'lim dasturi",
                'verbose_name_plural': "Ta'lim dasturlari",
                'ordering': ['name'],
            },
        ),
    ]
