# Generated by Django 6.1 on 2026-08-26 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_at', models.DateTimeField(auto_now_add=True, verbose_name='Kuzatuvga olingan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tracking', to='programs.program', verbose_name='Dastur')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_programs', to='accounts.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Kuzatilayotgan dastur',
                'verbose_name_plural': 'Kuzatilayotgan dasturlar',
                'ordering': ['-tracked_at'],
                'unique_together': {('student', 'program')},
            },
        ),
    ]
