# Generated by Django 6.1 on 2026-08-27 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_birth_date_student_birth_year_and_more'),
        ('programs', '0002_studentprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Universitet nomi')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Shahar')),
                ('world_ranking', models.IntegerField(blank=True, null=True, verbose_name='Jahon reytingi (QS/THE)')),
                ('website_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Rasmiy vebsayt')),
                ('acceptance_rate', models.FloatField(blank=True, null=True, verbose_name='Qabul foizi (%)')),
                ('average_cost_usd', models.IntegerField(blank=True, null=True, verbose_name="O'rtacha yillik xarajat ($)")),
                ('description', models.TextField(blank=True, default='', verbose_name='Universitet haqida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
            ],
            options={
                'verbose_name': 'Universitet',
                'verbose_name_plural': 'Universitetlar',
                'ordering': ['world_ranking', 'name'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Dastur tavsifi'),
        ),
        migrations.AddField(
            model_name='program',
            name='field_of_study',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name="Yo'nalish sohasi"),
        ),
        migrations.AddField(
            model_name='program',
            name='grant_coverage',
            field=models.CharField(blank=True, default='toliq_grant', max_length=100, verbose_name='Grant qamrovi'),
        ),
        migrations.AddField(
            model_name='program',
            name='min_gpa',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimal GPA (4.0 shkala)'),
        ),
        migrations.AddField(
            model_name='program',
            name='min_ielts',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimal IELTS bali'),
        ),
        migrations.AddField(
            model_name='program',
            name='min_sat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimal SAT bali'),
        ),
        migrations.AddField(
            model_name='program',
            name='min_toefl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimal TOEFL iBT bali'),
        ),
        migrations.CreateModel(
            name='StudentTargetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_programs_data', models.JSONField(blank=True, default=list, verbose_name="Zaxira dasturlar ro'yxati (JSON)")),
                ('match_score', models.IntegerField(default=0, verbose_name="Moslik ko'rsatkichi (%)")),
                ('selected_at', models.DateTimeField(auto_now=True, verbose_name='Tanlangan vaqt')),
                ('notes', models.TextField(blank=True, default='', verbose_name="O'quvchi izohi")),
                ('backup_programs', models.ManyToManyField(blank=True, related_name='backup_target_students', to='programs.program', verbose_name='Zaxira dasturlar')),
                ('primary_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_target_students', to='programs.program', verbose_name='Asosiy maqsad dastur')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target_selection', to='accounts.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "O'quvchining maqsadli tanlovi",
                'verbose_name_plural': "O'quvchilarning maqsadli tanlovlari",
                'ordering': ['-selected_at'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='programs.university', verbose_name='Universitet'),
        ),
    ]
