# Generated by Django 6.1 on 2026-08-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_university_program_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprogram',
            options={'ordering': ['-status_updated_at'], 'verbose_name': 'Kuzatilayotgan dastur / Ariza holati', 'verbose_name_plural': 'Kuzatilayotgan dasturlar / Arizalar'},
        ),
        migrations.AddField(
            model_name='studentprogram',
            name='decision_at',
            field=models.DateField(blank=True, null=True, verbose_name='Qaror sanasi'),
        ),
        migrations.AddField(
            model_name='studentprogram',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Shaxsiy izohlar'),
        ),
        migrations.AddField(
            model_name='studentprogram',
            name='status',
            field=models.CharField(choices=[('tracking', 'Kuzatilmoqda'), ('preparing', 'Hujjatlar tayyorlanmoqda'), ('submitted', 'Ariza topshirildi'), ('interview', 'Suhbatga taklif qilindi'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi'), ('waitlisted', "Kutish ro'yxatida"), ('withdrawn', 'Bekor qilindi')], default='tracking', max_length=20, verbose_name='Holat'),
        ),
        migrations.AddField(
            model_name='studentprogram',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Holat yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='studentprogram',
            name='submitted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Topshirilgan sana'),
        ),
    ]
