# Generated by Django 6.1 on 2026-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_studentprogram_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='scope',
            field=models.CharField(choices=[('international', 'Xalqaro'), ('domestic', "O'zbekiston ichida")], default='international', max_length=20, verbose_name='Dastur miqyosi'),
        ),
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('grant', "To'liq Grant / Stipendiya"), ('partial_grant', 'Qisman Grant'), ('paid', "To'lovli"), ('exchange', 'Almashinuv dasturi'), ('application_system', 'Qabul tizimi / Portal')], default='grant', max_length=100, verbose_name='Dastur turi'),
        ),
    ]
