# Generated by Django 6.1 on 2026-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_program_scope_alter_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Dastur muqova rasmi (Cover Photo)'),
        ),
        migrations.AddField(
            model_name='university',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Universitet rasmi (Campus Photo)'),
        ),
    ]
