# Generated by Django 6.1 on 2026-08-26 08:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('grammar', 'Grammar')], max_length=50, verbose_name="Ko'nikma")),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ball (0-100)')),
                ('raw_response', models.TextField(blank=True, default='', verbose_name="O'quvchi javobi")),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='Topshirilgan vaqt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_results', to='accounts.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Diagnostika natijasi',
                'verbose_name_plural': 'Diagnostika natijalari',
                'ordering': ['-taken_at'],
            },
        ),
    ]
