# Generated by Django 6.1 on 2026-08-27 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_birth_date_student_birth_year_and_more'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL iBT'), ('sat', 'SAT'), ('duolingo', 'Duolingo English Test (DET)'), ('cefr', 'CEFR / Milliy sertifikat')], max_length=50, verbose_name='Sertifikat turi')),
                ('test_date', models.DateField(verbose_name='Imtihon topshirilgan sana')),
                ('overall_score', models.FloatField(verbose_name='Umumiy ball')),
                ('section_scores', models.JSONField(blank=True, default=dict, verbose_name="Bo'limlar bo'yicha ballar")),
                ('is_valid', models.BooleanField(default=True, verbose_name="Amal qilish muddati to'g'ri (<= 3 yil)")),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_certificates', to='accounts.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Test sertifikati',
                'verbose_name_plural': 'Test sertifikatlari',
                'ordering': ['-test_date', '-created_at'],
            },
        ),
    ]
